# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-12 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0003_auto_20170412_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
