# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-12 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0005_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='sector',
            new_name='apply',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='content',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='order',
        ),
    ]
