# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-24 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0007_auto_20170413_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Text',
        ),
    ]
