# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0008_auto_20170524_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=4)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.Sector')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
