# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-27 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0013_truefalsequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='prompt',
            field=models.TextField(default=''),
        ),
    ]
